"""initial_tables

Revision ID: 9862f9c0fe7a
Revises: 
Create Date: 2026-03-18 23:18:52.291439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9862f9c0fe7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dct'
    )
    op.create_index('ix_dictionaries_active', 'dictionaries', ['active'], unique=False, schema='dct')
    op.create_index('ix_dictionaries_code', 'dictionaries', ['code'], unique=False, schema='dct')
    op.create_table('elements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('dictionary_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('index_sort', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dct'
    )
    op.create_index('ix_elements_code', 'elements', ['code'], unique=False, schema='dct')
    op.create_index('ix_elements_dictionary_id', 'elements', ['dictionary_id'], unique=False, schema='dct')
    op.create_index('ix_elements_parent_id', 'elements', ['parent_id'], unique=False, schema='dct')
    op.create_table('road_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='references'
    )
    op.create_index('ix_road_edges_source', 'road_edges', ['source'], unique=False, schema='references')
    op.create_index('ix_road_edges_source_target', 'road_edges', ['source', 'target'], unique=False, schema='references')
    op.create_index('ix_road_edges_target', 'road_edges', ['target'], unique=False, schema='references')
    op.create_table('road_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('lon', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('lat', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='references'
    )
    op.create_index('ix_road_nodes_lon_lat', 'road_nodes', ['lon', 'lat'], unique=False, schema='references')
    op.create_index('ix_road_nodes_node_id', 'road_nodes', ['node_id'], unique=True, schema='references')
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uwi', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('well_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='references'
    )
    op.create_index('ix_wells_lat_lon', 'wells', ['latitude', 'longitude'], unique=False, schema='references')
    op.create_index('ix_wells_uwi', 'wells', ['uwi'], unique=True, schema='references')
    op.create_table('wialon_units_snapshot_1',
    sa.Column('wialon_id', sa.BigInteger(), nullable=False),
    sa.Column('nm', sa.Text(), nullable=True),
    sa.Column('cls', sa.Integer(), nullable=True),
    sa.Column('mu', sa.Integer(), nullable=True),
    sa.Column('pos_t', sa.BigInteger(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('registration_plate', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('wialon_id'),
    schema='references'
    )
    op.create_index('ix_wialon_snap1_wialon_id', 'wialon_units_snapshot_1', ['wialon_id'], unique=False, schema='references')
    op.create_table('wialon_units_snapshot_2',
    sa.Column('wialon_id', sa.BigInteger(), nullable=False),
    sa.Column('nm', sa.Text(), nullable=True),
    sa.Column('cls', sa.Integer(), nullable=True),
    sa.Column('mu', sa.Integer(), nullable=True),
    sa.Column('pos_t', sa.BigInteger(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('registration_plate', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('wialon_id'),
    schema='references'
    )
    op.create_index('ix_wialon_snap2_wialon_id', 'wialon_units_snapshot_2', ['wialon_id'], unique=False, schema='references')
    op.create_table('wialon_units_snapshot_3',
    sa.Column('wialon_id', sa.BigInteger(), nullable=False),
    sa.Column('nm', sa.Text(), nullable=True),
    sa.Column('cls', sa.Integer(), nullable=True),
    sa.Column('mu', sa.Integer(), nullable=True),
    sa.Column('pos_t', sa.BigInteger(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('registration_plate', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('wialon_id'),
    schema='references'
    )
    op.create_index('ix_wialon_snap3_wialon_id', 'wialon_units_snapshot_3', ['wialon_id'], unique=False, schema='references')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wialon_snap3_wialon_id', table_name='wialon_units_snapshot_3', schema='references')
    op.drop_table('wialon_units_snapshot_3', schema='references')
    op.drop_index('ix_wialon_snap2_wialon_id', table_name='wialon_units_snapshot_2', schema='references')
    op.drop_table('wialon_units_snapshot_2', schema='references')
    op.drop_index('ix_wialon_snap1_wialon_id', table_name='wialon_units_snapshot_1', schema='references')
    op.drop_table('wialon_units_snapshot_1', schema='references')
    op.drop_index('ix_wells_uwi', table_name='wells', schema='references')
    op.drop_index('ix_wells_lat_lon', table_name='wells', schema='references')
    op.drop_table('wells', schema='references')
    op.drop_index('ix_road_nodes_node_id', table_name='road_nodes', schema='references')
    op.drop_index('ix_road_nodes_lon_lat', table_name='road_nodes', schema='references')
    op.drop_table('road_nodes', schema='references')
    op.drop_index('ix_road_edges_target', table_name='road_edges', schema='references')
    op.drop_index('ix_road_edges_source_target', table_name='road_edges', schema='references')
    op.drop_index('ix_road_edges_source', table_name='road_edges', schema='references')
    op.drop_table('road_edges', schema='references')
    op.drop_index('ix_elements_parent_id', table_name='elements', schema='dct')
    op.drop_index('ix_elements_dictionary_id', table_name='elements', schema='dct')
    op.drop_index('ix_elements_code', table_name='elements', schema='dct')
    op.drop_table('elements', schema='dct')
    op.drop_index('ix_dictionaries_code', table_name='dictionaries', schema='dct')
    op.drop_index('ix_dictionaries_active', table_name='dictionaries', schema='dct')
    op.drop_table('dictionaries', schema='dct')
    # ### end Alembic commands ###
